
FROM python:3.12-slim

# Set working dir
WORKDIR /app

# Copy and install requirements first (for caching)
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy all code
COPY . .


CMD python scripts/setup/init_db.py --skip-index && \
    alembic -x sqlalchemy.url=$DATABASE_URL upgrade head && \
    python scripts/setup/load_data.py --initialize-schema && \
    python scripts/setup/seed_loader.py --reset-sequences