services:
  - type: web
    name: comp0073_app
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: standard # Upgraded to match render plan
    branch: main
    healthCheckPath: /docs
    envVars:
      - key: POSTGRES_USER
        fromDatabase:
          name: comp0073_production_pgvector
          property: user
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: comp0073_production_pgvector
          property: password
      - key: POSTGRES_DB
        fromDatabase:
          name: comp0073_production_pgvector
          property: database
      - key: POSTGRES_HOST
        fromDatabase:
          name: comp0073_production_pgvector
          property: host
      - key: POSTGRES_PORT
        fromDatabase:
          name: comp0073_production_pgvector
          property: port
      - key: DATABASE_URL
        fromDatabase:
          name: comp0073_production_pgvector
          property: connectionString
      - key: SECRET_KEY
        sync: false # Set in dashboard
      - key: OPENAI_API_KEY
        sync: false # Set in dashboard
    numInstances: 1

#Once-off database setup service (to run migrations and create tables -- uncomment if redeploying)
# - type: web
#   name: db-setup-temp
#   runtime: docker
#   dockerfilePath: ./Dockerfile.setup
#   plan: free
#   branch: main
#   healthCheckPath: / # Dummy, since it won't serve traffic
#   envVars:
#     - key: POSTGRES_USER
#       fromDatabase:
#         name: comp0073_production_pgvector
#         property: user
#     - key: POSTGRES_PASSWORD
#       fromDatabase:
#         name: comp0073_production_pgvector
#         property: password
#     - key: POSTGRES_DB
#       fromDatabase:
#         name: comp0073_production_pgvector
#         property: database
#     - key: POSTGRES_HOST
#       fromDatabase:
#         name: comp0073_production_pgvector
#         property: host
#     - key: POSTGRES_PORT
#       fromDatabase:
#         name: comp0073_production_pgvector
#         property: port
#     - key: DATABASE_URL # This was already here—keep it!
#       fromDatabase:
#         name: comp0073_production_pgvector
#         property: connectionString
#     - key: SECRET_KEY
#       sync: false
#     - key: OPENAI_API_KEY
#       sync: false
#   numInstances: 1

databases:
  - name: comp0073_production_pgvector
    postgresMajorVersion: 17
    databaseName: comp0073
    user: admin
